"""Bit-exact comparison of prepare_dataset_npy_from_raw_video across two code states.

Runs ``prepare_dataset_npy_from_raw_video`` on a small mp4 sample and
compares ``_pos.npy`` / ``_joints.npy`` / ``_failed.npy`` against a reference
directory generated by a previous invocation of this same script. Used to gate
refactor branches that touch the pose-extraction path: main writes a reference,
branch reads it and compares.

Post-migration this runs the **rtmlib** 2D path (CPU-capable). Byte-exactness vs
the OLD mmpose extract is NOT expected -- the model changed by design; this gates
rtmlib-path refactors (rtmlib-main vs rtmlib-branch), so both the reference and
the test side must be generated on the rtmlib path.

Required env vars:
  CLIPS_DIR       -- dir with N small mp4s to re-extract pose from
  REFERENCE_DIR   -- dir holding reference _pos / _joints / _failed npys for
                     the same stems (populated by the main-side invocation;
                     see Usage)
  SCRATCH_DIR     -- where this invocation writes its outputs
                     (must NOT collide with REFERENCE_DIR or CLIPS_DIR)

Optional env vars:
  ATOL_FLOAT   -- tolerance for _pos and _joints (default: 1e-5; absorbs
                  projection-chain float rounding)
  POSE_DEVICE  -- rtmlib adapter device: "cpu" (default, deterministic) or "cuda"

Usage on bourbaki / engelbart (dual-invocation main-vs-branch):

  cd ~/badminton_cv_annotator
  source <rtmlib-venv>/bin/activate   # rtmlib + onnxruntime; mmpose not needed

  # Pick 5-10 stems and symlink their mp4s. Hit-zone stems are a good default
  # because their raw NPYs are also covered by the failsafe gate.
  mkdir -p /tmp/prepare_2d_smoke_clips/sample
  rm -f /tmp/prepare_2d_smoke_clips/sample/*
  stems=$(sort docs/architecture_notes/busted_hit_zone_clips_phase1.txt \\
              | sed -n '1p;172p;343p;515p;686p;858p;1029p;1201p;1372p;1544p')
  for stem in $stems; do
      find "$BST_X_CLIPS_DIR" -name "${stem}.mp4" \\
          -exec ln -sf {} /tmp/prepare_2d_smoke_clips/sample/${stem}.mp4 \\;
  done

  # STEP 1 -- populate the main-side reference. REFERENCE_DIR points at any
  # existing _pos/_joints/_failed dir (the script's comparison line on this
  # pass is ignored; we only want SCRATCH_DIR populated).
  git checkout main
  rm -rf /tmp/prepare_2d_smoke_main /tmp/prepare_2d_smoke_branch
  mkdir -p /tmp/prepare_2d_smoke_main /tmp/prepare_2d_smoke_branch
  CLIPS_DIR=/tmp/prepare_2d_smoke_clips \\
  REFERENCE_DIR="$BST_X_RTMPOSE_NPY_DIR" \\
  SCRATCH_DIR=/tmp/prepare_2d_smoke_main \\
  PYTHONPATH=src:src/bst_x \\
      python src/bst_x/validation_scripts/refactoring/smoke_prepare_2d_bit_exact.py

  # STEP 2 -- the real gate on the branch.
  git checkout <refactor-branch>
  CLIPS_DIR=/tmp/prepare_2d_smoke_clips \\
  REFERENCE_DIR=/tmp/prepare_2d_smoke_main \\
  SCRATCH_DIR=/tmp/prepare_2d_smoke_branch \\
  PYTHONPATH=src:src/bst_x \\
      python src/bst_x/validation_scripts/refactoring/smoke_prepare_2d_bit_exact.py

A passing run prints ``PASS: N stems matched`` for every stem.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import numpy as np


def _compare_stem(scratch_dir: Path, ref_dir: Path, stem: str, atol: float) -> tuple[bool, str]:
    """Compare _pos / _joints / _failed for one stem; return (ok, message)."""
    new_pos = np.load(scratch_dir / f"{stem}_pos.npy")
    new_joints = np.load(scratch_dir / f"{stem}_joints.npy")
    new_failed = np.load(scratch_dir / f"{stem}_failed.npy")

    ref_pos = np.load(ref_dir / f"{stem}_pos.npy")
    ref_joints = np.load(ref_dir / f"{stem}_joints.npy")
    ref_failed = np.load(ref_dir / f"{stem}_failed.npy")

    if new_pos.shape != ref_pos.shape:
        return False, f"pos shape mismatch: {new_pos.shape} vs {ref_pos.shape}"
    if new_joints.shape != ref_joints.shape:
        return False, f"joints shape mismatch: {new_joints.shape} vs {ref_joints.shape}"
    if new_failed.shape != ref_failed.shape:
        return False, f"failed shape mismatch: {new_failed.shape} vs {ref_failed.shape}"

    if not np.array_equal(new_failed, ref_failed):
        n_diff = int((new_failed != ref_failed).sum())
        return False, f"failed differs on {n_diff} frames"

    pos_max = float(np.abs(new_pos - ref_pos).max())
    joints_max = float(np.abs(new_joints - ref_joints).max())
    if pos_max > atol or joints_max > atol:
        return False, f"floats above atol: pos_max={pos_max:.3e} joints_max={joints_max:.3e}"

    return True, f"pos_max={pos_max:.3e} joints_max={joints_max:.3e}"


def main() -> int:
    clips_dir = Path(os.environ["CLIPS_DIR"]).resolve()
    reference_dir = Path(os.environ["REFERENCE_DIR"]).resolve()
    scratch_dir = Path(os.environ["SCRATCH_DIR"]).resolve()
    atol = float(os.environ.get("ATOL_FLOAT", "1e-5"))

    if not clips_dir.is_dir():
        raise FileNotFoundError(f"CLIPS_DIR not found: {clips_dir}")
    if not reference_dir.is_dir():
        raise FileNotFoundError(f"REFERENCE_DIR not found: {reference_dir}")
    if scratch_dir.resolve() in (clips_dir.resolve(), reference_dir.resolve()):
        raise ValueError(
            "SCRATCH_DIR must not collide with CLIPS_DIR or REFERENCE_DIR; "
            "would overwrite reference data."
        )
    scratch_dir.mkdir(parents=True, exist_ok=True)

    clips = sorted(clips_dir.glob("**/*.mp4"))
    if not clips:
        raise ValueError(f"No mp4 files under {clips_dir}")
    print(f"CLIPS_DIR     : {clips_dir}  ({len(clips)} mp4s)")
    print(f"REFERENCE_DIR : {reference_dir}")
    print(f"SCRATCH_DIR   : {scratch_dir}")
    print(f"ATOL_FLOAT    : {atol}")
    print()

    # The active homography uses ShuttleSet's set_info + my_raw_video_resolution.
    import pandas as pd  # noqa: PLC0415
    from pipeline.config import RESOLUTION_CSV_PATH, SET_INFO_DIR  # noqa: PLC0415
    from shared.court import build_all_court_info  # noqa: PLC0415
    from preparing_data.prepare_train_on_shuttleset import (  # noqa: PLC0415
        prepare_dataset_npy_from_raw_video,
    )

    res_df = pd.read_csv(RESOLUTION_CSV_PATH).set_index("id")
    all_court_info = build_all_court_info(SET_INFO_DIR, res_df)

    # Run the rtmlib pose step. CPU by default (onnxruntime CPU is
    # deterministic, so rtmlib-vs-rtmlib is bit-exact for unchanged code);
    # POSE_DEVICE=cuda to match a GPU-generated reference.
    prepare_dataset_npy_from_raw_video(
        my_clips_folder=clips_dir,
        save_root_dir=scratch_dir,
        resolution_df=res_df,
        all_court_info=all_court_info,
        joints_normalized_by_v_height=False,
        joints_center_align=True,
        device=os.environ.get("POSE_DEVICE", "cpu"),
    )

    print()
    print("=== Comparison vs reference ===")
    n_ok = 0
    n_fail = 0
    for clip in clips:
        stem = clip.stem
        ok, msg = _compare_stem(scratch_dir, reference_dir, stem, atol)
        flag = "PASS" if ok else "FAIL"
        print(f"  [{flag}] {stem}: {msg}")
        if ok:
            n_ok += 1
        else:
            n_fail += 1

    print()
    print(f"PASS: {n_ok}/{len(clips)} stems matched (atol={atol})")
    if n_fail:
        print(f"FAIL: {n_fail}/{len(clips)} stems mismatched")
    return 0 if n_fail == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
